data_args:
    batch_size : 32
    shuffle : True
    num_workers : 4
    pin_memory : True

encoder_args:
    node_feat : 16
    edge_feat : 8
    node_embed_dim : 64
    edge_embed_dim : 64
    hidden_dim : 128
    num_layers : 3
    heads : 4
    set2set_steps : 3
    latent_dim : 128
    dropout : 0.0

decoder_args:
    template_khop: 2
    node_embed_dim: 10
    edge_embed_dim: 10
    hidden_dim: 128
    num_layers: 3
    heads: 4
    dropout_mp: 0.0
    dropout_mlp: 0.0
    mlp_layers: 2
    rbf_dim: 10
    rbf_min: 0.0
    rbf_max: 5.0
    rbf_gamme: 10.0

propagator_args:
    seqlength: 5
    predlength: 1
    hidden_dim: 128
    lstm_layers: 2
    heads: 4
    dropout: 0.1