debug: False
outpath: ./train_runs/tft_e2e
outfolder: run
overwrite: False
nexp: 5
output_to_file: True

# Trainer Settings
nepochs: 1000
weight_decay: 0.0
nolog: False
wand: True
wand_project: SurrogateDynamics
wand_entity: goharalisiddiqui-tum
scheduler: True
lrate: 0.001
loss_prop_weight: 0.01
loss_rec_weight: 1.0
loss_e2e_weight: 1.0
loss_encdec_weights: [1.0, 1.0, 1.0, 1.0] # bond, angle, dihedral_cos, dihedral_sin

dynamics_name: XTC
data_args:
    xtcfile: ./data_generation/ala2/300K/ala2_100ns/md.xtc
    tprfile: ./data_generation/ala2/300K/ala2_100ns/md.tpr
    selection: "(resname ALA or resname ACE or resname NME) and not element H"
    train_size : 1000
    batch_size : 32
    validation_size : 200
    val_batch_size : 32
    dataset_type : "GRAPH"
    num_workers : 4
    norm_type : "minmax"

encoder_args:
    node_feat : 3 # Should come from data
    edge_feat : 3 # Should come from data
    node_embed_dim : 16
    edge_embed_dim : 16
    hidden_dim : 256
    num_layers : 4
    heads : 4
    set2set_steps : 3
    latent_dim : 64
    dropout : 0.0

decoder_args:
    template_khop: 2
    node_embed_dim: 16
    edge_embed_dim: 16
    hidden_dim: 256
    num_layers: 3
    heads: 4
    dropout_mp: 0.0
    dropout_mlp: 0.0
    final_mlp_layers: 2
    rbf_dim: 16
    rbf_min: 0.0
    rbf_max: 4.0
    rbf_gamma: 10.0

propagator_name: BGE_TFT
propagator_args:
    input_chunk_length: 5
    output_chunk_length: 1
    hidden_dim: 128
    lstm_layers: 1
    num_attention_heads: 2
    dropout: 0.0