debug: False
outpath: ./train_runs/tft/cg/gaussian_regression
outfolder: run
overwrite: True
nexp: 1
output_to_file: True

# Trainer Settings
nepochs: 2000
weight_decay: 0.0
wandb: True
wandb_project: SurrogateDynamics-Propagator-CG
wandb_entity: goharalisiddiqui-tum
lrate: 0.001
# likelihood: LogNormal
# likelihood_args:
#     prior_mu: 0.0
#     prior_sigma: 1.0
#     prior_strength: 0.5
# likelihood: Laplace
# likelihood_args:
#     prior_mu: 0.0
#     prior_b: 3.0
#     prior_strength: 0.5
likelihood: Gaussian
likelihood_args:
    prior_mu: 0.0
    prior_sigma: 1.0
    prior_strength: 0.0
    beta_nll: 1.0 # Weight for NLL loss. [0,1] 0 -> MSE, 1 -> NLL, High values means high weight on low error points
# likelihood: QuantileRegression
# likelihood_args:
#     quantiles: [0.1,0.15,0.2,0.5,0.8,0.85,0.9]
data_analyser: ala2
early_stopping: False
scheduler: True
scheduler_args:
    factor: 0.5
    patience: 20
    min_lr: 0.00000001

dynamics_name: XTC_graph
data_args:
    xtcfile: ./data_generation/ala2/solvated/300K/ala2_100ns/md.xtc
    tprfile: ./data_generation/ala2/solvated/300K/initialization/tpr_initial.tpr
    selection: "(resname ALA or resname ACE or resname NME) and not element H"
    datareader_type: "XTC_CHUNKS_CG"
    cg_window: 32
    train_size : 20
    batch_size : 2
    validation_size : 4
    val_batch_size : 2
    dataset_type : "GRAPH"
    num_workers : 1
    n_seq_per_sample : 32
    norm_type : "minmax"

propagator_name: TFT
encdec_name: BGE
encdec_ckpt: /mnt/projects/sne/Gohar/12.PROJECT_Surrogate_Dynamics/surrogate-dynamics/train_runs/bge/run_2/checkpoints/best.ckpt
propagator_args:
    input_chunk_length: 8
    output_chunk_length: 8
    hidden_dim: 128
    lstm_layers: 4
    num_attention_heads: 4
    dropout: 0.0