debug: False
outpath: ./predict_runs/propagator/tft/cg/gaussian_regression
outfolder: train_run_6/run
overwrite: True
nexp: 1
output_to_file: True 
plot_decoded: False


#####################################################################
# E2E Model of Ala2
#####################################################################
dynamics_name: XTC_graph
data_args:
    datareader_type: "XTC"
    datareader_args:
        xtcfile: ./data_generation/ala2/solvated/300K/ala2_100ns/md.xtc
        tprfile: ./data_generation/ala2/solvated/300K/initialization/tpr_initial.tpr
        selection: "(resname ALA or resname ACE or resname NME) and not element H"
    dataset_type : "GRAPH"
    predict_steps : 5000
    # predict_batch_size : 800

propagator_name: TFT
propagator_ckpt: train_runs/propagator/tft/cg/gaussian_regression/run_6/checkpoints/saved.ckpt
sampling_temperature: 1.0
# propagator_ckpt: ./train_runs/tft_e2e_gaussian/run_20/checkpoints/best.ckpt

writer_name: ala2
writer_args:
    kde_sigma: 0.2
    kde_bin_x: 200
    kde_bin_y: 200
    minima_tolerance: 0.5
    n_minima_compare: 3
    n_BFGS_runs: 100
#####################################################################


#####################################################################
# Separate Latent and Propagation Models
#####################################################################
# dynamics_name: XTC
# data_args:
#     xtcfile: ./data_generation/ala2/300K/ala2_100ns/md.xtc
#     tprfile: ./data_generation/ala2/300K/ala2_100ns/md.tpr
#     selection: "(resname ALA or resname ACE or resname NME) and not element H"
#     dataset_type : "GRAPH"
#     predict_size : 100
#     batch_size : 32

# propagator_name: BGE_TFT
# propagator_ckpt: ./tft_e2e/run/checkpoints/best.ckpt
#####################################################################