debug: False
outpath: ./train_runs/
outfolder: run_test
overwrite: True
nexp: 1
output_to_file: True

# Trainer Settings
nepochs: 2
weight_decay: 0.0
nolog: False
wandb: False
wandb_project: SurrogateDynamics-E2E-CG
wandb_entity: goharalisiddiqui-tum
lrate: 0.0005
loss_prop_weight: 0.01
loss_prop_start: 200 # Start propagation loss after these many epochs
loss_rec_weight: 0.99
loss_e2e_weight: 0.0
loss_encdec_weights: [0.01, 0.01, 0.49, 0.49] # bond, angle, dihedral_cos, dihedral_sin
likelihood: Gaussian
likelihood_args:
    prior_mu: 0.0
    prior_sigma: 1.0
    prior_strength: 0.0
    beta_nll: 1.0 # Weight for NLL loss. [0,1] 1 -> MSE, 0 -> NLL, High values can mitigate issues with NLL causing effective under-sampling of poorly fit
# likelihood: Laplace
# likelihood_args:
#     prior_mu: 0.0
#     prior_b: 3.0
#     prior_strength: 0.5
# likelihood: Quantile
# likelihood_args:
#     quantiles: [0.45,0.46,0.47,0.48,0.49,0.5,0.51,0.52,0.53,0.54,0.55]

early_stopping: False
data_analyser: ala2
scheduler: True
scheduler_args:
    factor: 0.5
    patience: 20
    min_lr: 0.00000001

#load_ckpt: /mnt/projects/sne/Gohar/12.PROJECT_Surrogate_Dynamics/surrogate-dynamics/train_runs/tft_e2e_gaussian/run_15/checkpoints/best.ckpt

dynamics_name: XTC_graph
data_args:
    xtcfile: ./data_generation/ala2/solvated/300K/ala2_100ns/md.xtc
    tprfile: ./data_generation/ala2/solvated/300K/initialization/tpr_initial.tpr
    selection: "(resname ALA or resname ACE or resname NME) and not element H"
    datareader_type: "XTC_CHUNKS_CG"
    cg_window: 1
    train_size : 10
    batch_size : 2
    validation_size : 4
    val_batch_size : 2
    dataset_type : "GRAPH"
    num_workers : 1
    n_seq_per_sample : 2
    norm_type : "minmax"

encoder_args:
    node_feat : 3 # Should come from data
    edge_feat : 3 # Should come from data
    node_embed_dim : 8
    edge_embed_dim : 4
    hidden_dim : 64
    num_layers : 5
    heads : 8
    set2set_steps : 3
    latent_dim : 256
    dropout : 0.0

decoder_args:
    template_khop: 3
    node_embed_dim: 8
    edge_embed_dim: 8
    hidden_dim: 64
    num_layers: 5
    heads: 4
    dropout_mp: 0.0
    dropout_mlp: 0.1
    final_mlp_layers: 3
    rbf_dim: 16
    rbf_min: 0.0
    rbf_max: 4.0
    rbf_gamma: 10.0

propagator_name: BGE_TFT
propagator_args:
    input_chunk_length: 8
    output_chunk_length: 8
    hidden_dim: 128
    lstm_layers: 4
    num_attention_heads: 4
    dropout: 0.0